### ISSUE TITLE
FEATURE REQUEST: Localized RULES.INI support

### ISSUE THREAD

**Issue by jaredballou** [djfdyuruiry/cnc-td-nco-mod#3]
Every time the mod is updated, the RULES.INI file changes, and I need to redo my edits to get back to where I was. It would be nice if I could have a RULES.LOCAL.INI that I create in the same directory, with only the changes to be applied, and have that merged in after the main RULES.INI gets loaded?

Example RULES.LOCAL.INI:

```
; Local overrides only so that we don't need to edit the main RULES.INI.
; Copy and paste any sections from the RULES.INI and make edits to them in here.
[NCO]
LogLevel=debug
EnableLuaScripts=true
LuaScripts=my_lua_script.lua

[Game]
EnableDebugLogging=true
AllowBuildingAllForCurrentHouse=true
MvcRedeployable=true
MaxBuildDistance=2
HideRocketLauncherFromNod=false

HideRocketLauncherFromGdiUntilScenario9=false

; Commando
[RMBO]
ScenarioLevel=1

; Rocket Launcher
[MSAM]
Prerequisite=
ScenarioLevel=1
Houses=MULTI1,MULTI2,MULTI3,MULTI4,MULTI5,MULTI6,JP,BADGUY,GOODGUY

; S.S.M. Launcher
[MLRS]
ScenarioLevel=1
Houses=MULTI1,MULTI2,MULTI3,MULTI4,MULTI5,MULTI6,JP,GOODGUY,BADGUY
```

**Comment by djfdyuruiry** [comment]
Sounds like a sensible idea. Will have a look at it, should just be a matter of having a fall back for the local rules file to defult and the rules themeselves.

**Comment by jaredballou** [comment]
Yeah, either way would be good. I like the way you laid it out in the 1.3 MR.

**Comment by djfdyuruiry** [comment]
Added in v1.3
