### ISSUE TITLE
2 issues that I found

### ISSUE THREAD

**Issue by BladeXcorpio** [djfdyuruiry/cnc-td-nco-mod#31]
The first issue that I found, is that when I try to change the houses, it doesn't work, same thing when I try "HelipadsAndAircraftBoughtSeperately". I only use your mod.

**Comment by djfdyuruiry** [comment]
Hey @BladeXcorpio 

I have fixed the Houses issues in v2.4 - let me know if you have any issues with that

Still looking at the `HelipadsAndAircraftBoughtSeperately` flag not working, I suspect this is something broken by the latest C&C patch

**Comment by BladeXcorpio** [comment]
Thanks, I'll check out. Btw awesome mod

**Comment by djfdyuruiry** [comment]
Thanks 😊

**Comment by jaredballou** [comment]
This seems to be closed out now. Please reopen/resubmit if you still have trouble. Thanks!

**Comment by jaredballou** [comment]
This seems to be closed out now. Please reopen/resubmit if you still have trouble. Thanks!
